// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
<<<<<<<< HEAD:WebApplication1/Migrations/20251105182146_InitialCreate.Designer.cs
    [Migration("20251105182146_InitialCreate")]
========
    [Migration("20251113151155_InitialCreate")]
>>>>>>>> main:WebApplication1/Migrations/20251113151155_InitialCreate.Designer.cs
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

<<<<<<<< HEAD:WebApplication1/Migrations/20251105182146_InitialCreate.Designer.cs
            modelBuilder.Entity("WebApplication1.Data.Models.Krankschreibung", b =>
========
            modelBuilder.Entity("WebApplication1.Areas.Zeiterfassung.Models.TimeEntry", b =>
>>>>>>>> main:WebApplication1/Migrations/20251113151155_InitialCreate.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

<<<<<<<< HEAD:WebApplication1/Migrations/20251105182146_InitialCreate.Designer.cs
                    b.Property<DateTime>("Bis")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErfasstAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MitAttest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MitarbeiterEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MitarbeiterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Von")
========
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSpan")
                        .IsRequired()
>>>>>>>> main:WebApplication1/Migrations/20251113151155_InitialCreate.Designer.cs
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

<<<<<<<< HEAD:WebApplication1/Migrations/20251105182146_InitialCreate.Designer.cs
                    b.ToTable("Krankschreibung");
========
                    b.ToTable("TimeEntries");
>>>>>>>> main:WebApplication1/Migrations/20251113151155_InitialCreate.Designer.cs
                });

            modelBuilder.Entity("WebApplication1.Models.LoginUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoginUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$zrTCmdAmPwGwA5YDE8JLe.NmjU7B7A9Ng9KWxkEimi8qdNlfJlnx2",
                            Role = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            IsActive = true,
                            PasswordHash = "$2a$11$v7swAPsNfVs53z2/kj7cvuB8fB1UV2u5DpQS71yphoim1NiX6GbES",
                            Role = 2,
                            UserName = "hr"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
